---
- name: Create VM from Proxmox Template
  hosts: all
  tasks:
#    - name: Install python3-pip
#      ansible.builtin.apt:
#        name: python3-pip
#        state: present
#      become: yes

    - name: Install pip using apt
      apt:
        name: python3-pip
        state: present
        update_cache: yes
        force: yes
        become: yes

    - name: Install setuptools module via pip
      ansible.builtin.pip:
        name: setuptools
        state: present

    - name: Install requests module via pip
      ansible.builtin.pip:
        name: requests
        state: present

    - name: Install proxmoxer module via pip
      ansible.builtin.pip:
        name: proxmoxer
        state: present

    - name: Start VM
      community.general.proxmox:
        api_host: 192.168.1.140
        api_user: "dave@pam"
        api_password: "4d8849df-4c52-43c7-a1e5-e4ef31d0a769"
        node: "daveServer"
        vmid: 101
        state: started
