---
- name: Manage Proxmox hosts
  hosts: all
  vars:
    proxmox_node:  "daveServer"                                         # Proxmox node
    ansible_python_interpreter: /root/venv/bin/python
  
  tasks:
    - name: Print database credentials
      debug:
        msg: 
          - "api_host: {{ api_host }}"
          - "api_user: {{ api_user }}"
          - "api_token_id: {{ api_token_id }}"
          - "api_token_secret: {{ api_token_secret }}"


    - name: List all existing virtual machines on node
      community.general.proxmox_vm_info:
        api_host: "{{ api_host }}"
        api_user:  "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ proxmox_node }}"
      register: vm_list
    
    - name: List all QEMU virtual machines on node
      community.general.proxmox_vm_info:
        api_host: "{{ api_host }}"
        api_user:  "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ proxmox_node }}"
        type: qemu
      register: lxc_list

    - name: Print VM variables
      debug:
        msg: 
          - "{{ item }}"
#          - "vm list: {{ vm_list }}"
#          - "Container list: {{ lxc_list }}"
      loop: "{{vm_list | json_query('results[?type==`LXC`].vmid')}}"
