---
- name: Manage Proxmox hosts
  hosts: all
  vars:
    proxmox_node:  "daveServer"                                         # Proxmox node
    ansible_python_interpreter: /root/venv/bin/python
  
  tasks:
    - name: Print database credentials
      debug:
        msg: 
          - "api_host: {{ api_host }}"
          - "api_user: {{ api_user }}"
          - "api_token_id: {{ api_token_id }}"
          - "api_token_secret: {{ api_token_secret }}"


    - name: List all existing virtual machines on node
      community.general.proxmox_vm_info:
        api_host: "{{ api_host }}"
        api_user:  "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ proxmox_node }}"
        type: lxc
      register: lxc_list 
    
    - name: List all QEMU virtual machines on node
      community.general.proxmox_vm_info:
        api_host: "{{ api_host }}"
        api_user:  "{{ api_user }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ proxmox_node }}"
        type: qemu
      register: vm_list

    - name: Print VM variables
      debug:
        msg: 
#          - "{{ item }}"
          - "vm list: {{ vm_list | json_query('proxmox_vms[*].vmid') }}"
          - "Container list: {{ lxc_list | json_query('proxmox_vms[*].vmid') }}"
#      loop: "{{vm_list | json_query('proxmox_vms[?type==`lxc`].vmid')}}"
