---
- name: Manage Proxmox hosts
  hosts: all
  tasks:
    - name: Print database credentials
      debug:
        msg: 
          - "api_host: {{ api_host }}"
          - "api_user: {{ api_user }}"
          - "api_token_id: {{ api_token_id }}"
          - "api_token_secret: {{ api_token_secret }}"


    - name: List all existing virtual machines on node
      community.general.proxmox_vm_info:
        api_host: proxmoxhost
        api_user: root@pam
        api_token_id: '{{ token_id | default(omit) }}'
        api_token_secret: '{{ token_secret | default(omit) }}'
        node: node01
      register: vm_list
    
    - name: List all QEMU virtual machines on node
      community.general.proxmox_vm_info:
        api_host: proxmoxhost
        api_user: root@pam
        api_password: '{{ password | default(omit) }}'
        node: node01
        type: qemu
      register: lxc_list

    - name: Print VM variables
      debug:
        msg: 
          - "vm list: {{ vm_list }}"
          - "Container list: {{ lxc_list }}"
