- name: Update Linux VMs
  hosts: all
  become: true
  tasks:  
    - name: Update apt packages    
      apt:
        update_cache: yes
    - name:  Upgrade apt packages    
      apt:
        upgrade: yes
