---
- name: Manage Proxmox hosts
  hosts: all
  gather_facts: false

  vars:
    proxmox_node:  "daveServer"                                         # Proxmox node
    ansible_python_interpreter: /root/venv/bin/python

  tasks:      
    - name: Stop VM's we started
      community.general.proxmox_kvm:
        api_host: "{{ api_host }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}
        api_user: "{{ api_user }}"
        node: "daveServer"
        vmid: "{{ item }}"
        state: stopped
      loop:  "{{wf_vm_status | json_query('results[?status==`stopped`].vmid')}}"
