---
- name: Manage Proxmox hosts
  hosts: all
  gather_facts: false

  vars:
    proxmox_node:  "daveServer"                                         # Proxmox node
    ansible_python_interpreter: /root/venv/bin/python
    vm_ids:
          - 101
          - 103
          - 104
          - 105
          - 106
          - 107
          - 108

  tasks:

    - name: Start VM
      community.general.proxmox_kvm:
        api_host: "{{api_host}}"
        api_token_id: "{{api_token_id}}"
        api_token_secret: "{{api_token_secret}}"
        api_user: "{{api_user}}"
        node: "{{proxmox_node}}"
        vmid: "{{ item }}"
        state: started
      loop:  "{{ vm_ids }}"
      register: vm_status
    - name: Set a variable for the workflow
      ansible.builtin.set_stats:
        data:
          wf_vm_status: "{{ vm_status }}"
